'0':
  hotels_near: []
  type: 2
'1':
  hotels_near:
    - Fujiyama
  type: 0
'2':
  hotels_near:
    - Fujiyama
    - Boomerang
  type: 1
'3':
  hotels_near:
    - Fujiyama
    - Boomerang
  type: 0
'4':
  hotels_near:
    - Fujiyama
    - Boomerang
  type: 1
'5':
  hotels_near:
    - Fujiyama
    - Boomerang
  type: 0
'6':
  hotels_near:
    - Fujiyama
  type: 3
'7':
  hotels_near: []
  type: 0
'8':
  hotels_near:
    - Etoile
  type: 1
'9':
  hotels_near:
    - Etoile
    - President
  type: 1
'10':
  hotels_near:
    - Etoile
    - President
  type: 2
'11':
  hotels_near:
    - Royal
    - President
  type: 1
'12':
  hotels_near:
    - Royal
    - President
  type: 0
'13':
  hotels_near:
    - Royal
    - President
  type: 1
'14':
  hotels_near:
    - Royal
    - President
  type: 0
'15':
  hotels_near:
    - Royal
    - President
  type: 1
'16':
  hotels_near:
    - Royal
    - Waikiki
  type: 0
'17':
  hotels_near:
    - Royal
    - Waikiki
  type: 1
'18':
  hotels_near:
    - Royal
    - Waikiki
  type: 3
'19':
  hotels_near:
    - Royal
    - Waikiki
  type: 0
'20':
  hotels_near:
    - Royal
    - Waikiki
  type: 1
'21':
  hotels_near:
    - Etoile
    - Taj_Mahal
  type: 1
'22':
  hotels_near:
    - Etoile
    - Taj_Mahal
  type: 0
'23':
  hotels_near:
    - Etoile
    - Taj_Mahal
  type: 1
'24':
  hotels_near:
    - Etoile
    - Taj_Mahal
  type: 2
'25':
  hotels_near:
    - Taj_Mahal
  type: 0
'26':
  hotels_near:
    - Safari
  type: 0
'27':
  hotels_near:
    - Safari
  type: 0
'28':
  hotels_near:
    - Etoile
    - Safari
  type: 1
'29':
  hotels_near:
    - Etoile
    - Safari
  type: 3
'30':
  hotels_near:
    - Safari
  type: 0
'-1':
  hotels_near: []
  type: 4

